version: "3.9"

services:
  app1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app1

  app2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app2

  app3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app3

  app_group:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app_group

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf_runtime/nginx.conf:/etc/nginx/nginx.conf:ro,z


    depends_on:
      - app1
      - app2
      - app3
      - app_group
